### PR TITLE
Update to 0.78.1

### PR DESCRIPTION
**Pull request by rderooy**
- Convert from autotools to meson build system
- add FluidSynth
- add Munt (mt32emu)
- Add libslirp

Tested on a local flatpak repo.

### CODE REVIEW

**Comment by Eonfge** [comment]
_copy-pasta_

-----
@rderooy  Wow, what a timing, I just finished most of my PR. Could we combine our changes into one merge request:
https://github.com/Eonfge/io.github.dosbox-staging/commit/0f42581edbf5896649a507986d677d84a893af5f

I would recommend you to change two things;
- use static archives for downloading the packages
- use release-monitoring hooks so that Flathub can automatically create pull-requests when there are updates

It sounds like a small thing, but using anitya for dependency monitoring makes maintaining packages a lot easier.

**Comment by Eonfge** [comment]
bot, build

**Comment by rderooy** [comment]
bot, build

**Comment by Eonfge** [comment]
@hfiguiere Are you able to merge this request, and to close #1 which is outdated. We also need to appoint a new maintainer since @dreamer has been absent for a long time, so perhaps it's best if I and @rderooy take over for the time being.

**Comment by hfiguiere** [comment]
merged.

I can't invite contributors though.

**Comment by kcgen** [comment]
@Eonfge ,

> perhaps it's best if I and @rderooy take over for the time being.

I support this suggestion.

**Pull request merged**
