### PR TITLE
Upstream sdl

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
We'll need to test this first. Not sure if all features are included upstream

**Comment by Eonfge** [comment]
@JakobDev Works for me, but best if you also take a look

**Comment by Eonfge** [comment]
@JakobDev Let me know what you think. Else, I'll give this one a go.

**Comment by Eonfge** [comment]
bot, build

**Comment by JakobDev** [comment]
I don't have that much experience with SDL. If it works, than you should merge it.

**Comment by prodrigestivill** [comment]
This removal broke the app when using it with `SDL_AUDIODRIVER=pipewire`.

This is caused since the runtime sdl didn't came with pipewire enabled and the one build by libSDL2.yml was. So I already created an issue hoping if this can be fixed in the runtime at [freedesktop-sdk!1638](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1638).

Finally they have already fixed but it is still pending to be merged the backport into 23.08 (MR at [freedesktop-sdk!15503](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15503)), so hopefully next 23.08 release will have this fixed.

I don't think it is needed any further action to be made, just as a report in case somebody else is affected.

**Pull request merged**
